# .github/workflows/pages.yml
name: Build & Deploy GH Pages

on:
  push:
    branches: [ main ]          # change if your default branch differs
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ───────────────────────────── 1. checkout ───────────────────────────
    - uses: actions/checkout@v4

    # ───────────────────── 2. inject username / password ─────────────────
    - name: Inject login hashes
      env:
        USER_HASH: ${{ secrets.QUIZ_USER_HASH }}
        PASS_HASH: ${{ secrets.QUIZ_PASS_HASH }}
      run: |
        sed -i "s/__USER_HASH__/$USER_HASH/" login/auth.js
        sed -i "s/__PASS_HASH__/$PASS_HASH/" login/auth.js

    # ──────────────── 3. build CSV list & patch quiz_app.html ────────────
    - name: Inject CSV list for quiz picker
      run: |
        # Grab every *.csv in login/, strip the path, keep the real filename
        LIST=$(ls -1 login/*.csv | sed 's#.*/##' | paste -sd "," -)
        # Replace the placeholder inside quiz_app.html
        sed -i "s|__CSV_LIST__|$LIST|" login/quiz_app.html

    # ────────────────────────── 4. upload artifact ───────────────────────
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .                 # root of your static site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
